config/routes.rb
Rails.application.routes.draw do
  get 'admin/new'

  get 'admin/create'

  get 'admin/destroy'

  get 'session/new'

  get 'session/create'

  get 'session/destroy'

  get '/search' => 'pages#search'

  get '/login' => 'session#new'

  post '/login' => 'session#create'

  delete '/logout' => 'session#destroy'

  root 'pages#search'

  resources :users
  resources :reservations
  resources :flights
  resources :airplanes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airplane
  has_many :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:airplane_id, :flight_number, :origin, :destination, :departure_date, :departure_time)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(flight) do |f| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :airplane_id %>
    <%= f.number_field :airplane_id %>
  </div>

  <div class="field">
    <%= f.label :flight_number %>
    <%= f.text_field :flight_number %>
  </div>

  <div class="field">
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>

  <div class="field">
    <%= f.label :destination %>
    <%= f.text_field :destination %>
  </div>

  <div class="field">
    <%= f.label :departure_date %>
    <%= f.date_field :departure_date %>
  </div>

  <div class="field">
    <%= f.label :departure_time %>
    <%= f.time_field :departure_time %>
  </div>

  <button class="btn waves-effect waves-light" type="submit" name="action"><%= f.submit %></button>
<% end %>

app/views/flights/edit.html.erb
<h1>Edit Flight</h1>

<%= render 'form', flight: @flight %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Airplane</th>
      <th>Flight number</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Departure date</th>
      <th>Departure time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.airplane_id %></td>
        <td><%= flight.flight_number %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.departure_date %></td>
        <td><%= flight.departure_time %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to 'New Flight', new_flight_path %></button>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Flight: <%= @flight.flight_number%></h1>

<div class="collection">
  <p class="collection-item">
    <strong>Airplane:</strong>
    <%= @flight.airplane_id %>
  </p>

  <p class="collection-item">
    <strong>Origin:</strong>
    <%= @flight.origin %>
  </p>

  <p class="collection-item">
    <strong>Destination:</strong>
    <%= @flight.destination %>
  </p>

  <p class="collection-item">
    <strong>Departure date:</strong>
    <%= @flight.departure_date %>
  </p>

  <p class="collection-item">
    <strong>Departure time:</strong>
    <%= @flight.departure_time %>
  </p>
</div>

<button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to 'Edit', edit_flight_path(@flight) %></button>
<button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to 'Back', flights_path %></button>


<!-- <h1>This is where backbone should be loaded</h1> -->