config/routes.rb
Rails.application.routes.draw do
  get 'admin/new'

  get 'admin/create'

  get 'admin/destroy'

  get 'session/new'

  get 'session/create'

  get 'session/destroy'

  get '/search' => 'pages#search'

  get '/login' => 'session#new'

  post '/login' => 'session#create'

  delete '/logout' => 'session#destroy'

  root 'pages#search'

  resources :users
  resources :reservations
  resources :flights
  resources :airplanes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :flights
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:name, :rows, :columns)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_for(airplane) do |f| %>
  <% if airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rows %>
    <%= f.number_field :rows %>
  </div>

  <div class="field">
    <%= f.label :columns %>
    <%= f.text_field :columns %>
  </div>

  <button class="btn waves-effect waves-light" type="submit" name="action"><%= f.submit %></button>
  
<% end %>

app/views/airplanes/edit.html.erb
<h1>Edit Airplane</h1>

<%= render 'form', airplane: @airplane %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airplanes</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Rows</th>
      <th>Columns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.name %></td>
        <td><%= airplane.rows %></td>
        <td><%= airplane.columns %></td>
        <td><%= link_to 'Show', airplane %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


    <button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to 'New Airplane', new_airplane_path %></button>

app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form', airplane: @airplane %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Airplane: <%= @airplane.name %></h1>

<div class="collection">

  <p class="collection-item">
    <strong>Rows:</strong>
    <%= @airplane.rows %>
  </p>

  <p class="collection-item">
    <strong>Columns:</strong>
    <%= @airplane.columns %>
  </p>
</div>

<button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to 'Edit', edit_airplane_path(@airplane) %></button>

<button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to 'Back', airplanes_path %></button>