config/routes.rb
Rails.application.routes.draw do
  get 'admin/new'

  get 'admin/create'

  get 'admin/destroy'

  get 'session/new'

  get 'session/create'

  get 'session/destroy'

  get '/search' => 'pages#search'

  get '/login' => 'session#new'

  post '/login' => 'session#create'

  delete '/logout' => 'session#destroy'

  root 'pages#search'

  resources :users
  resources :reservations
  resources :flights
  resources :airplanes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :flight
  belongs_to :user, optional: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:flight_id, :user_id, :rows, :columns)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight_id %>
    <%= f.number_field :flight_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :rows %>
    <%= f.number_field :rows %>
  </div>

  <div class="field">
    <%= f.label :columns %>
    <%= f.text_field :columns %>
  </div>

  <button class="btn waves-effect waves-light" type="submit" name="action"><%= f.submit %></button>
<% end %>

app/views/reservations/edit.html.erb
<h1>Edit Reservation</h1>

<%= render 'form', reservation: @reservation %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Flight</th>
      <th>Guest</th>
      <th>Rows</th>
      <th>Columns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.flight_id %></td>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.rows %></td>
        <td><%= reservation.columns %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to 'New Reservation', new_reservation_path %></button>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Reservation: <%= @reservation.id%></h1>

<div class="collection">
  <p class="collection-item">
    <strong>Flight:</strong>
    <%= @reservation.flight_id %>
  </p>

  <p class="collection-item">
    <strong>User:</strong>
    <%= @reservation.user_id %>
  </p>

  <p class="collection-item">
    <strong>Rows:</strong>
    <%= @reservation.rows %>
  </p>

  <p class="collection-item">
    <strong>Columns:</strong>
    <%= @reservation.columns %>
  </p>
</div>


<button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to 'Edit', edit_reservation_path(@reservation) %></button>
<button class="btn waves-effect waves-light" type="submit" name="action"><%= link_to 'Back', reservations_path %></button>